# Generated by Django 5.0.1 on 2024-02-16 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('new', 'new'), ('old', 'old')], max_length=100)),
                ('information', models.TextField()),
                ('deescription', models.TextField()),
                ('stock', models.CharField(choices=[('stock-in', 'stock-in'), ('stock-out', 'stock-out')], max_length=200)),
                ('status', models.CharField(choices=[('publish', 'publish'), ('draft', 'draft')], max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glamapp.brand')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glamapp.categories')),
                ('filter_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glamapp.filter_prize')),
            ],
        ),
    ]
